### PR TITLE
Use "mpp" from apt instead of building from source

### PR DESCRIPTION
**Pull request by seriyps**

### CODE REVIEW

**Comment by seriyps** [comment]
Hmm, apparently this only works on Radxa images. Or maybe they have a separate repo, let me check

**Comment by seriyps** [comment]
turned out to be more difficult than I expected. Will make another attempt later

**Comment by luastoned** [comment]
Does the Radxa repo include gst plugins for `mppvideodec` ?

**Comment by seriyps** [comment]
You can see what is in their repo here https://radxa-repo.github.io/bullseye/files.list

But the problem with this PR is that Radxa repo is obviusly not included in standard Debian image and for some reason my attempts to add it fail.

**Comment by luastoned** [comment]
Peeking into here https://radxa-repo.github.io/bullseye/pkgs.json I don't see librockchip-mpp-dev at all.

**Comment by JohnDGodwin** [comment]
> You can see what is in their repo here https://radxa-repo.github.io/bullseye/files.list
> 
> But the problem with this PR is that Radxa repo is obviusly not included in standard Debian image and for some reason my attempts to add it fail.

It's present and available in rsdk builds.

**Comment by seriyps** [comment]
Finally success. The trick was to add 2 repositories, not one:

```
deb [signed-by=/usr/share/keyrings/radxa-archive-keyring.gpg] https://radxa-repo.github.io/bullseye/ bullseye main
deb [signed-by=/usr/share/keyrings/radxa-archive-keyring.gpg] https://radxa-repo.github.io/bullseye rockchip-bullseye main
```

**Comment by JohnDGodwin** [comment]
> Finally success. The trick was to add 2 repositories, not one:
> 
> ```
> deb [signed-by=/usr/share/keyrings/radxa-archive-keyring.gpg] https://radxa-repo.github.io/bullseye/ bullseye main
> deb [signed-by=/usr/share/keyrings/radxa-archive-keyring.gpg] https://radxa-repo.github.io/bullseye rockchip-bullseye main
> ```
> 
> Now build takes ~4 minutes instead of ~8!

This is for Radxa only, for the orange pi series one must add a separate repo. I've been using this:
https://launchpad.net/~liujianfeng1994/+archive/ubuntu/rockchip-multimedia

**Comment by seriyps** [comment]
@JohnDGodwin  A-ha.. interesting.  Well, we are using this library here just to test that pixelpilot can be successfully compiled on Debian Bullseye on arm64 in GitHub CI. We can't run it for real in CI because we don't have actual rockchip available in CI.

Do you think building pixelpilot with Raspberry version of the library will make any difference?

**Comment by seriyps** [comment]
Or you saying we need to mention this PPA in the README?

**Pull request merged**
