### PR TITLE
Add command line option to print the list of supported screen modes

### LINKED ISSUE #25: Add --list-screenmodes arguments to list all supported scree modes
I want to know what screen mode supported by monitor, So, How about add --list-screenmodes arguments to list all supported scree modes.

### PR DESCRIPTION
**Pull request by seriyps**
Provides both "basic" and "verbose" modes.

On my monitor:

```
$ sudo pixelpilot --screen-mode-list 1
PixelPilot Rockchip 1.1
1920x1080@60
1920x1080@60
1920x1080@60
1920x1080@60
1920x1080@60
1920x1080@60
1920x1080@50
1920x1080@50
1920x1080@30
1920x1080@30
1920x1080@25
1920x1080@24
1920x1080@24
1600x1200@60
1680x1050@60
1280x1024@75
1280x1024@60
1152x864@75
...
```

```
$ sudo pixelpilot --screen-mode-list 2                                                                                                                                                    
PixelPilot Rockchip 1.1                                                                                                                                                                                      
connector id:111,width_mm:600,height_mm:340
mode name:1920x1080,pixel_clock:148352,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:PREFERRED|DRIVER                                                                                                                                                                                          
mode name:1920x1080,pixel_clock:148500,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1082,vsync_end:1087,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:DRIVER                                                                                                                                                                                                    
mode name:1920x1080,pixel_clock:148500,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:DRIVER                                                                                                                                                                                                    
mode name:1920x1080i,pixel_clock:74250,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1094,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC|INTERLACE,type:DRIVER
mode name:1920x1080i,pixel_clock:74250,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1094,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC|INTERLACE,type:DRIVER
mode name:1920x1080i,pixel_clock:74176,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1094,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC|INTERLACE,type:DRIVER                                                                                                                                                                                          
mode name:1920x1080,pixel_clock:148500,hdisplay:1920,hsync_start:2448,hsync_end:2492,htotal:2640,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:50,flags:PHSYNC|PVSYNC,type:DRIVER                                                                                                                                                                                                    
mode name:1920x1080i,pixel_clock:74250,hdisplay:1920,hsync_start:2448,hsync_end:2492,htotal:2640,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1094,vtotal:1125,vscan:0,vrefresh:50,flags:PHSYNC|PVSYNC|INTERLACE,type:DRIVER  
mode name:1920x1080,pixel_clock:74250,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:30,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1920x1080,pixel_clock:74176,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:30,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1920x1080,pixel_clock:74250,hdisplay:1920,hsync_start:2448,hsync_end:2492,htotal:2640,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:25,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1920x1080,pixel_clock:74250,hdisplay:1920,hsync_start:2558,hsync_end:2602,htotal:2750,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:24,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1920x1080,pixel_clock:74176,hdisplay:1920,hsync_start:2558,hsync_end:2602,htotal:2750,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:24,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1600x1200,pixel_clock:162000,hdisplay:1600,hsync_start:1664,hsync_end:1856,htotal:2160,hskew:0,vdisplay:1200,vsync_start:1201,vsync_end:1204,vtotal:1250,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:DRIVER
...
```

On my Walksnail X goggles:

```
$ sudo pixelpilot --screen-mode-list 2
PixelPilot Rockchip 1.1
connector id:111,width_mm:0,height_mm:0
mode name:1280x720,pixel_clock:74250,hdisplay:1280,hsync_start:1390,hsync_end:1430,htotal:1650,hskew:0,vdisplay:720,vsync_start:725,vsync_end:730,vtotal:750,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:PREFERRED
mode name:1920x1080,pixel_clock:148500,hdisplay:1920,hsync_start:2008,hsync_end:2052,htotal:2200,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:60,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1920x1080,pixel_clock:148500,hdisplay:1920,hsync_start:2448,hsync_end:2492,htotal:2640,hskew:0,vdisplay:1080,vsync_start:1084,vsync_end:1089,vtotal:1125,vscan:0,vrefresh:50,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:1280x720,pixel_clock:74250,hdisplay:1280,hsync_start:1720,hsync_end:1760,htotal:1980,hskew:0,vdisplay:720,vsync_start:725,vsync_end:730,vtotal:750,vscan:0,vrefresh:50,flags:PHSYNC|PVSYNC,type:DRIVER
mode name:720x576,pixel_clock:27000,hdisplay:720,hsync_start:732,hsync_end:796,htotal:864,hskew:0,vdisplay:576,vsync_start:581,vsync_end:586,vtotal:625,vscan:0,vrefresh:50,flags:NHSYNC|NVSYNC,type:DRIVER
mode name:720x480,pixel_clock:27000,hdisplay:720,hsync_start:736,hsync_end:798,htotal:858,hskew:0,vdisplay:480,vsync_start:489,vsync_end:495,vtotal:525,vscan:0,vrefresh:60,flags:NHSYNC|NVSYNC,type:DRIVER
```

Is this output format ok?
The maning of the verbose output parameters is not 100% clear for me, it is briefly documented here https://www.kernel.org/doc/html/latest/gpu/drm-kms.html#c.drm_display_mode

Fixes #25.

### CODE REVIEW

**Comment by zhouruixi** [comment]
1. Is verbose in need? I just want to be able to simply output the supported screen modes in resolution@refresh_rate format. That's easy to use. Use other tools like `edid-decode`  and `drm_info` for verbose.
2. If you think verbose is in need, --screen-mode-list <1, 2, 3> is not intuitive enough.

**Comment by seriyps** [comment]
1. Honestly I didn't know `drm_info` exists. Yep, maybe we don't need the verbose mode then
2. Yep, let's drop the argument completely

Why I wanted to introduce verbose mode initially is because when I connected my desktop display to Radxa, I saw the same mode repeated several times, so beame curious why there are duplicates and how are they different. However we don't have any way to select an exact mode right now, so evenif we output more info, we can't use this info in practive...

**Comment by zhouruixi** [comment]
1920x1080@60.00 have three modes on my monitor, This may be why there are so many duplicate screen modes.
│       │   ├───1920x1080@60.00 driver phsync pvsync 
│       │   ├───1920x1080@60.00 driver phsync pvsync 16:9 
│       │   ├───1920x1080@60.00 driver phsync pvsync interlace 16:9 

I think de-duplicate screen modes for --screen-mode-list is necessary.

**Comment by seriyps** [comment]
@zhouruixi updated; removed the verbosity argument and deduplicated (there still can be duplicates, but it should cover most cases)

**Pull request merged**
